version: "3.8"

services:

  nvidea-cuda:
    image: marcellodesales/nvidea-cuda-ubuntu
    build:
      context: .
      args:
        PYTHON_VERSION: 3.8
        CUDA_VERSION: 11.1.1
        NCCL_VERSION: 2.7.8  
        CUDNN_VERSION: 8.0.5.39
